version: "3.7"

services:
  pg:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: scratchy_phoenix_dev
      POSTGRES_USER: scratchy
      POSTGRES_PASSWORD: secret
      TZ: UTC
      PGTZ: UTC
    ports:
      - 30533:5432
#    volumes:
#      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1:
